<?php
    $config=array(
        'dbtype'=>array(
            'db_host'=>'localhost',
            'db_name'=>'wzl_db',
            'db_username'=>'root',
            'db_password'=>'',
            'db_charset'=>'utf8',
        ),
        'viewtype'=>array(
            'left_delimiter'=>'<{',
            'right_delimiter'=>'}>',
            'template_dir'=>ADMIN_PATH.'/admin/View/templates',
            'compile_dir'=>ADMIN_PATH.'/admin/View/templates_c',
            'caching'=>false,
            'cache_dir'=>ADMIN_PATH.'/admin/View/cache'
        )

    );